ProjectSkyfire/SkyFire_548

src/server/game/Entities/Object/Object.cpp, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Entities/Unit/Unit.h, src/server/game/Globals/ObjectMgr.cpp, src/server/game/Handlers/AddonHandler.cpp, src/server/game/Handlers/BlackMarketHandler.cpp, src/server/game/Handlers/CharacterHandler.cpp, src/server/game/Handlers/MiscHandler.cpp, src/server/game/Handlers/MovementHandler.cpp, src/server/game/Movement/MovementStructures.cpp, src/server/game/Movement/MovementStructures.h, src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp, src/server/scripts/Northrend/ChamberOfAspects/ObsidianSanctum/boss_sartharion.cpp
Not really sure what was meant by those if statements with comma... but the left side was useless in there
=> Misc: Multiple fixes

src/server/game/DataStores/DB2Stores.cpp
That log will not lie to me anymore
=> DataStores: fixed directory name for db2

CMakeLists.txt, src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Unit/Unit.cpp, src/server/game/Globals/ObjectMgr.h, src/server/game/Handlers/MovementHandler.cpp, src/server/game/Movement/MovementStructures.cpp, src/server/game/Movement/MovementStructures.h, src/server/game/Server/Protocol/Opcodes.cpp
Fixxed the Movement modifier and server no longer crash if a player type .mod speed 10 or else ... :)
=> Fix Movement Crash by modify movement speed

.travis.yml
Signed-off-by: AriDEV <aridev666@gmail.com>
=> Travis: Update Travis to Clang 3.7

sql/base/characters_database.sql, sql/updates/characters/2016_02_26_00_characters_character_stats.sql, src/server/game/Entities/Player/Player.cpp, src/server/scripts/Commands/cs_reload.cpp, src/server/shared/Database/Implementation/CharacterDatabase.cpp
Signed-off-by: AriDEV <aridev666@gmail.com>
=> Server/Player: Fixed saving blockpct into character_stats, also added mastery, pvpdamage and pvphealing.

src/server/game/Entities/Player/Player.cpp, src/server/game/Entities/Player/Player.h
People can stop pestering me about this now ^^.
=> Core/Quest: Fixed quest objectives being reset on save.

src/server/game/Handlers/MiscHandler.cpp
=> Server/PacketIO: Fix my mistake for packet HandleRequestAccountData

src/server/game/Scripting/ScriptLoader.cpp, src/server/scripts/Spells/CMakeLists.txt, src/server/scripts/Spells/spell_mastery.cpp
*Added an Update Spells:
spell_mastery_unshackled_fury
spell_mastery_shield_discipline
spell_mastery_combo_breaker
spell_mastery_blood_shield
spell_mastery_ignite
spell_mastery_hand_of_light
spell_mastery_elemental_overload
=> Core/Fixes: Added Spell Mastery

sql/updates/world/2016_09_18_00_world_sai.sql
https://github.com/ProjectSkyfire/SkyFire.548/issues/712
@SkyFire requested.
=> SmartAI misc npc

sql/updates/world/2016_10_24_00_world_spell_script_names.sql, src/server/scripts/Spells/spell_warrior.cpp
[Core/Spell]: Fix Warrior Raging Blow
=> [Core/Spell]: Fix Warrior Raging Blow

sql/updates/world/2017_02_29_00_world_misc.sql, src/server/game/Battlegrounds/Battleground.h, src/server/game/Battlegrounds/Zones/BattlegroundAB.cpp, src/server/game/Battlegrounds/Zones/BattlegroundBFG.cpp, src/server/game/Battlegrounds/Zones/BattlegroundBFG.h, src/server/game/Miscellaneous/Language.h
Added Battle for Gilneas / Recoded / Fixxed (Untested)
Windows Compiler give me 0 Error
14>------ Build started: Project: ALL_BUILD, Configuration: Debug x64 ------
15>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
15>Project not selected to build for this solution configuration
========== Build: 14 succeeded, 0 failed, 1 up-to-date, 1 skipped ==========
=> Added Battle for Gilneas / Recoded / Fixxed (Untested)

sql/updates/world/9999_99_99_99_spell_script_names.sql, src/server/scripts/Spells/spell_warrior.cpp
Updated bloodthirst for MoP
Updated deep wounds for MoP
Fixed 2P T16 DPS bonus.
It compiles no errors/warnings - Tested in game too.
=> Core/Scripts - Fix bloodthirst, deep wounds and T16 2P DPS bonus for warriors

src/server/collision/Management/MMapManager.cpp, src/server/collision/Management/VMapManager2.cpp, src/server/collision/Maps/MapTree.cpp, src/server/collision/Maps/TileAssembler.cpp, src/server/collision/VMapDefinitions.h, src/server/game/Maps/Map.cpp, src/server/game/Miscellaneous/SharedDefines.h, src/tools/map_extractor/System.cpp, src/tools/mmaps_generator/IntermediateValues.cpp, src/tools/mmaps_generator/MapBuilder.cpp, src/tools/mmaps_generator/MapBuilder.h, src/tools/mmaps_generator/PathGenerator.cpp, src/tools/mmaps_generator/TerrainBuilder.cpp, src/tools/vmap4_extractor/vmapexport.cpp
Core/Map: Fix Maps, Vmaps, Mmaps on mapids with more than 3 digits for example (Soo is 1136)
Need re-extract maps , vmaps and regenerate mmaps
=> Core/Map: Fix Maps, Vmaps, Mmaps on mapids with more than 3 digits for example (Soo is 1136)

src/server/scripts/Spells/spell_generic.cpp
=> Check SPELL_AURA_402 Script from @Ulduar.

sql/updates/world/2020_02_28_00_world.sql, src/server/scripts/Kalimdor/zone_mulgore.cpp
* Delete duplicate Kyle the Frenzied
* Fix Tender Strider Meat chance drop
* Fix waypoints Kyle the Frenzied
* Move from script to DB
=> DB/Quest: Fix Quest 11129 #842

dep/PackageList.txt, dep/zlib/adler32.c, dep/zlib/compress.c, dep/zlib/crc32.c, dep/zlib/deflate.c, dep/zlib/deflate.h, dep/zlib/gzguts.h, dep/zlib/gzlib.c, dep/zlib/gzread.c, dep/zlib/gzwrite.c, dep/zlib/infback.c, dep/zlib/inffast.c, dep/zlib/inflate.c, dep/zlib/inflate.h, dep/zlib/inftrees.c, dep/zlib/trees.c, dep/zlib/uncompr.c, dep/zlib/zconf.h, dep/zlib/zlib.h, dep/zlib/zutil.c, dep/zlib/zutil.h
Signed-off-by: SkyFire <admin@projectskyfire.org>
=> Update zlib to 1.2.11

.gitignore, src/server/scripts/Northrend/AzjolNerub/Ahnkahet/boss_prince_taldaram.cpp
And also added CLion files to .gitignore.
=> Fixed Prince Taldaram unreachable code

dep/acelite/ace/Process_Manager.cpp
Add work around to fix compile for Visual Studio.
Signed-off-by: SkyFire <admin@projectskyfire.org>
=> Core:Compile

src/server/game/Spells/SpellMgr.cpp
Thanks @AriDEV
Close https://github.com/ProjectSkyfire/SkyFire_548/issues/911
=> Core/Spell: Fix Remove Weapon Pandaren class mage

sql/updates/world/2020_09_15_00_world.sql
=> Fix Cheat Death crashing client

src/server/game/Spells/SpellEffects.cpp
- Removed additional combo point
- Recalculated damage mod
=> Rewrite Hemorrhage script

sql/updates/world/2021_01_25_00_world.sql, src/server/game/Entities/Unit/Unit.cpp
=> Improved Counterspell only proced with Counterspell

sql/updates/world/2021_02_08_00_world.sql, src/server/scripts/Spells/spell_priest.cpp
- Script Leap of Faith
- Script Body and Soul talent
- Script Glyph of Leap of Faith
- Drop obsolete Body and Soul script
=> Updated Leap of Faith and Body and Soul

sql/updates/world/2022_06_08_00_world.sql, sql/updates/world/2022_06_08_01_world.sql
=> Database/SAI: Wildscale Herbalist SAI

sql/updates/world/2022_06_08_02_world.sql, sql/updates/world/2022_06_08_03_world.sql
=> Database/SAI: Enraged Priest SAI

sql/updates/world/2022_06_08_03_world.sql, sql/updates/world/2022_06_08_04_world.sql
=> Database/SAI: Shan'ze Stonebender SAI

sql/updates/characters/2022_06_16_00_characters.sql
=> Fix worldserver crash on startup

sql/updates/world/world_2023_10_20_10_07.sql, src/server/game/Achievements/AchievementMgr.cpp, src/server/game/Achievements/AchievementMgr.h
*Now we can reward spell for some achievements
=> Core/Achievements: Implement Achievements Reward Spell

sql/updates/world/world_2023_11_01_23_52.sql, src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
Requirements:
https://github.com/ProjectSkyfire/SkyFire_548/pull/1183
https://github.com/ProjectSkyfire/SkyFire_548/pull/1185
=> Core/Script: Fix Quest "Death Comes From On High"

src/server/game/Server/Protocol/Opcodes.cpp
=> Core/Opcode: Fix "Leave Vehicle" button
